-- 1. Tạo cơ sở dữ liệu (tuỳ chọn)
-- CREATE DATABASE QuanLyPhongKham;
-- USE QuanLyPhongKham;
-- GO
use master 
drop database QuanLyPhongKham
-- 2. Bảng CHUCVU
CREATE TABLE CHUCVU (
    MaCV INT IDENTITY(1,1) PRIMARY KEY,
    TenCV NVARCHAR(100) NOT NULL
);
GO

-- 3. Bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV INT IDENTITY(1,1) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    MaCV INT NOT NULL,
    SDT VARCHAR(15),
    Email NVARCHAR(100),
    NgayVaoLam DATE,
    FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV)
);
GO

-- 4. Bảng BENHNHAN
CREATE TABLE BENHNHAN (
    MaBN INT IDENTITY(1,1) PRIMARY KEY,
    TenBN NVARCHAR(100) NOT NULL,
    Tuoi INT,
    SDT VARCHAR(15),
    DiaChi NVARCHAR(255),
    GioiTinh NVARCHAR(10),
    NgayTao DATE DEFAULT GETDATE(),
    NhomMau NVARCHAR(10),
    TrangThaiThanhToan NVARCHAR(50) DEFAULT N'Chưa thanh toán',
    GhiChu NVARCHAR(MAX),
    -- Lưu ý: Tổng tiền và tiền nợ nên tính từ hóa đơn, nhưng giữ lại nếu cần snapshot
    TongTien DECIMAL(18,2) DEFAULT 0,
    TienNo DECIMAL(18,2) DEFAULT 0
);
GO

-- 5. Bảng THUOC
CREATE TABLE THUOC (
    MaThuoc INT IDENTITY(1,1) PRIMARY KEY,
    TenThuoc NVARCHAR(100) NOT NULL,
    DVT NVARCHAR(20),
    DonGia DECIMAL(18,2) DEFAULT 0,
    SoLuongTon INT DEFAULT 0
);
GO

-- 6. Bảng DICHVU
CREATE TABLE DICHVU (
    MaDV INT IDENTITY(1,1) PRIMARY KEY,
    TenDV NVARCHAR(100) NOT NULL,
    GiaTien DECIMAL(18,2) NOT NULL
);
GO

-- 7. Bảng THONGTINCLS
CREATE TABLE THONGTINCLS (
    MaTTLS INT IDENTITY(1,1) PRIMARY KEY,
    NoiDungDieuTri NVARCHAR(MAX),
    MaDV INT,
    FOREIGN KEY (MaDV) REFERENCES DICHVU(MaDV)
);
GO

-- 8. Bảng CHAN DOAN
CREATE TABLE CHAN_DOAN (
    MaCD INT IDENTITY(1,1) PRIMARY KEY,
    NoiDung NVARCHAR(MAX) NOT NULL,
    NgayChuanDoan DATE DEFAULT GETDATE(),
    MaBN INT NOT NULL,
    MaNV INT, -- Ai chẩn đoán
    MaTTLS INT NULL,
    FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaTTLS) REFERENCES THONGTINCLS(MaTTLS)
);
GO

-- 9. Bảng DONTHUOC
CREATE TABLE DONTHUOC (
    MaDT INT IDENTITY(1,1) PRIMARY KEY,
    SoLuong INT NOT NULL,
    GhiChu NVARCHAR(MAX),
    -- Tổng tiền sẽ tính = SoLuong * DonGia (từ bảng THUOC)
    MaThuoc INT NOT NULL,
    FOREIGN KEY (MaThuoc) REFERENCES THUOC(MaThuoc)
);
GO

-- 10. Bảng HOADON
CREATE TABLE HOADON (
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    NgayLapHD DATE DEFAULT GETDATE(),
    TongTien DECIMAL(18,2) DEFAULT 0,
    MaBN INT NOT NULL,
    MaNV INT NOT NULL, 
    FOREIGN KEY (MaBN) REFERENCES BENHNHAN(MaBN),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
GO

-- 11. Bảng trung gian: Chi tiết hóa đơn (kết nối HOADON <-> DONTHUOC)
CREATE TABLE ChiTietHoaDon (
    MaCTHD INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    MaDT INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    ThanhTien AS (SoLuong * DonGia) PERSISTED,
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD) ON DELETE CASCADE,
    FOREIGN KEY (MaDT) REFERENCES DONTHUOC(MaDT) ON DELETE CASCADE
);
GO

-- 12. Bảng trung gian: Hóa đơn - Chẩn đoán (nếu cần)
CREATE TABLE HoaDon_ChanDoan (
    MaHD INT,
    MaCD INT,
    PRIMARY KEY (MaHD, MaCD),
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD) ON DELETE CASCADE,
    FOREIGN KEY (MaCD) REFERENCES CHAN_DOAN(MaCD) ON DELETE CASCADE
);
GO

-- 13. Bảng BAOCAODOANHTHU
CREATE TABLE BAOCAODOANHTHU (
    MaBCDT INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATE DEFAULT GETDATE(),
    MaHD INT,
    TongDoanhThu DECIMAL(18,2),
    SoLuongHoaDon INT,
    FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
);
GO